var societyCode =  [   
    ["AO", "Angola Society"],   
    ["AF", "Afghanistan Society"],   
    ["AL", "Albania Society"],   
    ["DZ", "Algeria Society"],   
    ["AD", "Andorra Society"],   
    ["AI", "Anguilla Society"],   
    ["AG", "Barbuda Antigua Society"],   
    ["AR", "Argentina Society"],   
    ["AM", "Armenia Society"],   
    ["AU", "Australia Society"],   
    ["AT", "Austria Society"],   
    ["AZ", "Azerbaijan Society"],   
    ["BS", "Bahamas Society"],   
    ["BH", "Bahrain Society"],   
    ["BD", "Bangladesh Society"],   
    ["BB", "Barbados Society"],   
    ["BY", "Belarus Society"],   
    ["BE", "Belgium Society"],   
    ["BZ", "Belize Society"],   
    ["BJ", "Benin Society"],   
    ["BM", "Bermuda Is. Society"],   
    ["BO", "Bolivia Society"],   
    ["BW", "Botswana Society"],   
    ["BR", "Brazil Society"],   
    ["BN", "Brunei Society"],   
    ["BG", "Bulgaria Society"],   
    ["BF", "Burkina-faso Society"],   
    ["MM", "Burma Society"],   
    ["BI", "Burundi Society"],   
    ["CM", "Cameroon Society"],   
    ["CA", "Canada Society"],   
    ["CF", "Central African Republic Society"],   
    ["TD", "Chad Society"],   
    ["CL", "Chile Society"],   
    ["CN", "China Society"],   
    ["CO", "Colombia Society"],   
    ["CG", "Congo Society"],   
    ["CK", "Cook Is. Society"],   
    ["CR", "Costa Rica Society"],   
    ["CU", "Cuba Society"],   
    ["CY", "Cyprus Society"],   
    ["CZ", "Czech Republic Society"],   
    ["DK", "Denmark Society"],   
    ["DJ", "Djibouti Society"],   
    ["DO", "Dominica Rep. Society"],   
    ["EC", "Ecuador Society"],   
    ["EG", "Egypt Society"],   
    ["SV", "EI Salvador Society"],   
    ["EE", "Estonia Society"],   
    ["ET", "Ethiopia Society"],   
    ["FJ", "Fiji Society"],   
    ["FI", "Finland Society"],   
    ["FR", "France Society"],   
    ["GF", "French Guiana Society"],   
    ["GA", "Gabon Society"],   
    ["GM", "Gambia Society"],   
    ["GE", "Georgia Society"],   
    ["DE", "Germany Society"],   
    ["GH", "Ghana Society"],   
    ["GI", "Gibraltar Society"],   
    ["GR", "Greece Society"],   
    ["GD", "Grenada Society"],   
    ["GU", "Guam Society"],   
    ["GT", "Guatemala Society"],   
    ["GN", "Guinea Society"],   
    ["GY", "Guyana Society"],   
    ["HT", "Haiti Society"],   
    ["HN", "Honduras Society"],   
    ["HU", "Hungary Society"],   
    ["IS", "Iceland Society"],   
    ["IN", "India Society"],   
    ["ID", "Indonesia Society"],   
    ["IR", "Iran Society"],   
    ["IQ", "Iraq Society"],   
    ["IE", "Ireland Society"],   
    ["IL", "Israel Society"],   
    ["IT", "Italy Society"],   
    ["JM", "Jamaica Society"],   
    ["JP", "Japan Society"],   
    ["JO", "Jordan Society"],   
    ["KH", "Kampuchea (Cambodia ) Society"],   
    ["KZ", "Kazakstan Society"],   
    ["KE", "Kenya Society"],   
    ["KR", "Korea Society"],   
    ["KW", "Kuwait Society"],   
    ["KG", "Kyrgyzstan Society"],   
    ["LA", "Laos Society"],   
    ["LV", "Latvia Society"],   
    ["LB", "Lebanon Society"],   
    ["LS", "Lesotho Society"],   
    ["LR", "Liberia Society"],   
    ["LY", "Libya Society"],   
    ["LI", "Liechtenstein Society"],   
    ["LT", "Lithuania Society"],   
    ["LU", "Luxembourg Society"],   
    ["MO", "Macao Society"],   
    ["MG", "Madagascar Society"],   
    ["MW", "Malawi Society"],   
    ["MY", "Malaysia Society"],   
    ["MV", "Maldives Society"],   
    ["ML", "Mali Society"],   
    ["MT", "Malta Society"],   
    ["MU", "Mauritius Society"],   
    ["MX", "Mexico Society"],   
    ["MD", "Moldova Society"],   
    ["MC", "Monaco Society"],   
    ["MN", "Mongolia Society"],   
    ["MS", "Montserrat Is. Society"],   
    ["MA", "Morocco Society"],   
    ["MZ", "Mozambique Society"],   
    ["NA", "Namibia Society"],   
    ["NR", "Nauru Society"],   
    ["NP", "Nepal Society"],   
    ["NL", "Netherlands Society"],   
    ["NZ", "New Zealand Society"],   
    ["NI", "Nicaragua Society"],   
    ["NE", "Niger Society"],   
    ["NG", "Nigeria Society"],   
    ["KP", "North Korea Society"],   
    ["NO", "Norway Society"],   
    ["OM", "Oman Society"],   
    ["PK", "Pakistan Society"],   
    ["PA", "Panama Society"],   
    ["PG", "Papua New Cuinea Society"],   
    ["PY", "Paraguay Society"],   
    ["PE", "Peru Society"],   
    ["PH", "Philippines Society"],   
    ["PL", "Poland Society"],   
    ["PF", "French Polynesia Society"],   
    ["PT", "Portugal Society"],   
    ["PR", "Puerto Rico Society"],   
    ["QA", "Qatar Society"],   
    ["RO", "Romania Society"],   
    ["RU", "Russia Society"],   
    ["LC", "Saint Lueia Society"],   
    ["VC", "Saint Vincent Society"],   
    ["SM", "San Marino Society"],   
    ["ST", "Sao Tome and Principe Society"],   
    ["SA", "Saudi Arabia Society"],   
    ["SN", "Senegal Society"],   
    ["SC", "Seychelles Society"],   
    ["SL", "Sierra Leone Society"],   
    ["SG", "Singapore Society"],   
    ["SK", "Slovakia Society"],   
    ["SI", "Slovenia Society"],   
    ["SB", "Solomon Is. Society"],   
    ["SO", "Somali Society"],   
    ["ZA", "South Africa Society"],   
    ["ES", "Spain Society"],   
    ["LK", "Sri Lanka Society"],   
    ["SD", "Sudan Society"],   
    ["SR", "Suriname Society"],   
    ["SZ", "Swaziland Society"],   
    ["SE", "Sweden Society"],   
    ["CH", "Switzerland Society"],   
    ["SY", "Syria Society"],   
    ["TW", "Taiwan Society"],   
    ["TJ", "Tajikstan Society"],   
    ["TZ", "Tanzania Society"],   
    ["TH", "Thailand Society"],   
    ["TG", "Togo Society"],   
    ["TO", "Tonga Society"],   
    ["TT", "Trinidad and Tobago Society"],   
    ["TN", "Tunisia Society"],   
    ["TR", "Turkey Society"],   
    ["TM", "Turkmenistan Society"],   
    ["UG", "Uganda Society"],   
    ["UA", "Ukraine Society"],   
    ["AE", "United Arab Emirates Society"],   
    ["GB", "United Kingdom Society"],   
    ["US", "United States of America Society"],   
    ["UY", "Uruguay Society"],   
    ["UZ", "Uzbekistan Society"],   
    ["VE", "Venezuela Society"],   
    ["VN", "Vietnam Society"],   
    ["YE", "Yemen Society"],   
    ["YU", "Yugoslavia Society"],   
    ["ZW", "Zimbabwe Society"],   
    ["ZR", "Zaire Society"],   
    ["ZM", "Zambia Society"]   
];

module.exports = societyCode;    